name: ReleaseToTestGallery
on: 
  workflow_dispatch:
jobs:
  PublishToPoshTestGallery:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Update PowerShell Metadata
        uses: natescherer/update-powershell-metadata-action@main
        with:
          path: src
          version: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
          copyright: (c) YYYY Nate Scherer. All rights reserved.
      - name: Publish Module to PoshTestGallery
        uses: natescherer/publish-powershell-action@main
        with:
          token: ${{ secrets.POSHTESTGALLERY_TOKEN }}
          target: testgallery
          path: src